window.quotes = [
    { text: "You have to believe in yourself when no one else does.", author: "Serena Williams" },
    { text: "When you have a dream, you’ve got to grab it and never let go.", author: "Carol Burnett" },
    { text: "The most important thing is to enjoy your life—to be happy—it’s all that matters.", author: "Steve Jobs" },
    { text: "Spread love everywhere you go. Let no one ever come without leaving happier.", author: "Mother Teresa" },
    { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { text: "The biggest adventure you can take is to live the life of your dreams.", author: "Oprah Winfrey" },
    { text: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
    { text: "When you reach the end of your rope, tie a knot in it and hang on.", author: "Franklin D. Roosevelt" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
    { text: "The biggest adventure you can take is to live the life of your dreams.", author: "Oprah Winfrey" },
    { text: "You’ve got to be in it to win it.", author: "Tony Robbins" },
    { text: "It does not matter how slowly you go, as long as you do not stop.", author: "Confucius" },
    { text: "Find out who you are and do it on purpose.", author: "Dolly Parton" },
    { text: "For me, becoming isn’t about arriving somewhere or achieving a certain aim. I see it instead as forward motion, a means of evolving, a way to reach continuously toward a better self. The journey doesn’t end.", author: "Michelle Obama" },
    { text: "Confident people have a way of carrying themselves that makes others attracted to them.", author: "Sofia Vergara" },
    { text: "If you can do what you do best and be happy, you are further along in life than most people.", author: "Leonardo DiCaprio" },
    { text: "You can be everything. You can be the infinite amount of things that people are.", author: "Kesha" },
    { text: "Always go with your passions. Never ask yourself if it’s realistic or not.", author: "Deepak Chopra" },
    { text: "When you change your thoughts, remember to also change your world.", author: "Norman Vincent Peale" },
    { text: "The more you know who you are, and what you want, the less you let things upset you.", author: "Stephanie Perkins" },
    { text: "By being yourself, you put something wonderful in the world that was not there before.", author: "Edwin Elliot" },
    { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
    { text: "It is never too late to be what you might have been.", author: "George Elliot" },
    { text: "Find out who you are and be that person. That’s what your soul was put on this earth to be. Find the truth, live that truth, and everything else will come.", author: "Ellen DeGeneres" },
    { text: "When we are no longer able to change a situation, we are challenged to change ourselves.", author: "Viktor E. Frankl" },
    { text: "If you cannot do great things, do small things in a great way.", author: "Napoleon Hill" },
    { text: "Always do your best. What you plant now, you will harvest later.", author: "Og Mandino" },
    { text: "Get busy living or get busy dying.", author: "Stephen King" },
    { text: "In three words I can sum up everything I’ve learned about life: It goes on.", author: "Robert Frost" },
    { text: "You can’t help what you feel, but you can help how you behave.", author: "Margaret Atwood" },
    { text: "No need to hurry. No need to sparkle. No need to be anybody but oneself.", author: "Virginia Woolf" },
    { text: "Promise me you’ll always remember: You’re braver than you believe, and stronger than you seem, and smarter than you think.", author: "A. A. Milne" },
    { text: "Failure is a great teacher and, if you are open to it, every mistake has a lesson to offer.", author: "Oprah Winfrey" },
    { text: "If you don’t like the road you’re walking, start paving another one.", author: "Dolly Parton" },
    { text: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
    { text: "Keep smiling, because life is a beautiful thing and there’s so much to smile about.", author: "Marilyn Monroe" },
    { text: "Be persistent and never give up hope.", author: "George Lucas" },
    { text: "When we strive to become better than we are, everything around us becomes better too.", author: "Paulo Coelho" },
    { text: "Believe and act as if it were impossible to fail.", author: "Charles Kettering" },
    { text: "There are so many great things in life; why dwell on negativity?", author: "Zendaya" },
    { text: "Happiness often sneaks in through a door you didn’t know you left open.", author: "John Barrymore" },
    { text: "Always remember that you are absolutely unique. Just like everyone else.", author: "Margaret Mead" },
    { text: "Keep your face towards the sunshine and shadows will fall behind you.", author: "Walt Whitman" },
    { text: "A problem is a chance for you to do your best.", author: "Duke Ellington" },
    { text: "You don’t always need a plan. Sometimes you just need to breathe, trust, let go and see what happens.", author: "Mandy Hale" },
    { text: "Nothing is impossible. The word itself says ‘I’m possible!’", author: "Audrey Hepburn" },
    { text: "Life does not have to be perfect to be wonderful.", author: "Annette Funicello" },
    { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
    { text: "The best way out is through.", author: "Robert Frost" },
    { text: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { text: "Whether you think you can or you can’t, you’re right.", author: "Henry Ford" },
    { text: "Don’t take yourself too seriously. Know when to laugh at yourself, and find a way to laugh at obstacles that inevitably present themselves.", author: "Halle Bailey" },
    { text: "Love the life you live. Live the life you love.", author: "Bob Marley" },
    { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
    { text: "I’m not going to continue knocking that old door that doesn’t open for me. I’m going to create my own door and walk through that.", author: "Ava DuVernay" },
    { text: "If you change the way you look at things, the things you look at change.", author: "Wayne Dyer" },
    { text: "I believe that if you’ll just stand up and go, life will open up for you. Something just motivates you to keep moving.", author: "Tina Turner" },
    { text: "Once you face your fear, nothing is ever as hard as you think.", author: "Olivia Newton-John" },
    { text: "Next time, ask ‘What’s the worst that will happen?’ Then push yourself a little further than you dare.", author: "Audre Lorde" },
    { text: "Dreams do not come true just because you dream them. It’s hard work that makes things happen. It’s hard work that creates change.", author: "Shonda Rhimes" },
    { text: "Let us make our future now, and let us make our dreams tomorrow’s reality.", author: "Malala Yousafzai" },
    { text: "You will face many defeats in life, but never let yourself be defeated.", author: "Maya Angelou" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "Take the time to enjoy the little things, for one day you may look back and realize they were the big things.", author: "Robert Brault" },
    { text: "The future is not something we enter. The future is something we create.", author: "Leonard I. Sweet" },
    { text: "Life has got those twists and turns. You’ve got to hold on tight and off you go.", author: "Nicole Kidman" },
    { text: "The future belongs to those who prepare for it today.", author: "Malcolm X" },
    { text: "Don’t wait around for other people to be happy for you. Any happiness you get you’ve got to make yourself.", author: "Alice Walker" },
    { text: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { text: "Life is a long lesson in humility.", author: "James M. Barrie" },
    { text: "You define your own life. Don’t let other people write your script.", author: "Oprah Winfrey" },
    { text: "We must let go of the life we have planned, so as to accept the one that is waiting for us.", author: "Joseph Campbell" },
    { text: "We make a living by what we get, but we make a life by what we give.", author: "Winston Churchill" },
    { text: "Mistakes are a fact of life. It is the response to the error that counts.", author: "Nikki Giovanni" },
    { text: "When I let go of what I am, I become what I might be.", author: "Lao Tzu" },
    { text: "Ignore your mistakes. The number one thing to worry about is: Am I doing what I’m good at?", author: "Max Levchin" },
    { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
    { text: "Life has no limitations, except the ones you make.", author: "Les Brown" },
    { text: "In the end, it’s not the years in your life that count. It’s life in your years.", author: "Abraham Lincoln" },
    { text: "You may not control all the events that happen to you, but you can decide not to be reduced by them.", author: "Maya Angelou" },
    { text: "Life is a succession of lessons which must be lived to be understood.", author: "Ralph Waldo Emerson" },
    { text: "Dreaming, after all, is a form of planning.", author: "Gloria Steinem" },
    { text: "We become what we think about most of the time.", author: "Earl Nightingale" },
    { text: "Life is very interesting…in the end, some of your greatest pains become your greatest strengths.", author: "Drew Barrymore" },
    { text: "Life is a daring adventure or it is nothing at all.", author: "Helen Keller" },
    { text: "I had that familiar conviction that life was beginning over again with the summer.", author: "F. Scott Fitzgerald" },
    { text: "Life is made of ever so many partings welded together.", author: "Charles Dickens" },
    { text: "My interest is in the future because I am going to spend the rest of my life there.", author: "Charles Kettering" },
    { text: "Life is what happens to you when you are busy making other plans.", author: "John Lennon" },
    { text: "Yesterday is but today’s memory and tomorrow is today’s dream.", author: "Khalil Gibran" },
    { text: "It’s amazing how a little tomorrow can make up for a whole lot of yesterday.", author: "John Guare" },
];